apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-k8s-service-deployment
  labels:
    app: supplier-k8s-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-k8s-service
  template:
    metadata:
      labels:
        app: supplier-k8s-service
    spec:
      containers:
        - name: supplier-k8s-service
          image: himantha98/supplier-service
          port:
          - containerPort: 9093